### ISSUE TITLE
[BCSV] Enable the editor to add fields

### ISSUE THREAD

**Issue by Lord-Giganticus** [SMGCommunity/Whitehole-Neo#32] opened 2024-03-06 19:21 UTC
Giving users the ability to add fields to a bcsv in the editor where needed would be a interesting feature, we would need to make sure the hash and all that is parsed correctly however.

**Comment by AwesomeTMC** [comment] 2024-03-06 22:34
Duplicate of #30.

**Closed by AwesomeTMC** 2024-03-06 22:34 UTC
Labels: enhancement
